### ISSUE TITLE
Mutiselect doesn't allows to clear all items

### ISSUE THREAD

**Issue by fenixkim** [distantnative/multiselect#13]
Hi, I want to clear all the previously selected items from a multiselect field leaving it empty. When I save the page it refresh without saving any change in the field. It only happens when I unselect all the items from the list.

That could be happening here?

**Comment by distantnative** [comment]
Hmm, I can't reproduce it myself. Can you please provide the part of your blueprint?

**Comment by kopfnuss** [comment]
Hi, 
I can confirm the issue. I have just tried it with a fresh Kirby starterkit (version 2.2.3) and the most recent multiselect field type, using the example from the readme:
```
bestband:
  label: Best Band Ever
  type: multiselect
  required: true
  search: true
  options:
    1d : 1Direction
    bb: BBoys
    aq: Aqua
```

Selecting. adding, and changing items works. However when deselecting *all* items and saving, the http POST request does not contain the bestband[] field anymore. It is therefore ignored by the panel and the previous value is restored.

This screenshot shows the form data headers of the POST request (an item is selected)

![image](https://cloud.githubusercontent.com/assets/1991584/12960094/4a995268-d031-11e5-8b40-b02a6a00e3bc.png)

This screenshot shows the form data headers of the POST request (*no* item is selected)

![image](https://cloud.githubusercontent.com/assets/1991584/12960104/5a54d5ba-d031-11e5-93ed-d606dc37b1a5.png)

**Comment by fenixkim** [comment]
@kopfnuss Thanks for the explanation, that is exactly the issue.

**Comment by samnabi** [comment]
I can confirm this as well.

**Comment by distantnative** [comment]
If you are using the example exactly as posted, it includes `required: true` - so that sets that you are not able to save the field without any selection. Without it, it works for me. Have you tried without the `required` option?

**Comment by samnabi** [comment]
I'm getting the issue even without `required`.

```
  products:
    label: Products
    type: multiselect
    options: query
    query: 
      page: shop
      fetch: pages
      template: product
```
