### ISSUE TITLE
Multiselect doesn't lose focus when switching to the next field

### ISSUE THREAD

**Issue by samnabi** [distantnative/multiselect#2]
Multiselect should collapse and lose focus when I click on another field.

![screenshot 2015-06-14 09 43 13](https://cloud.githubusercontent.com/assets/1731536/8148780/3708288e-127a-11e5-89a5-9ff993c68f87.png)

**Comment by distantnative** [comment]
Will try to fix this over the next few days.

Potential connected problems:
- Unfocus when clicked on other multiselect field
- Unfocus on focus change via keys (tab)

**Comment by distantnative** [comment]
Hmm, I can actually not reproduce that error :/ Could you share your blueprint?

But I fixed my concern with the unfocus on tab key

**Comment by samnabi** [comment]
The fields shown above are within a `structure` field. Maybe that's the issue.

```
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  shipping:
    label: Shipping methods
    type: structure
    entry: {{method}}
    fields:
      method:
        label: Method
        help: e.g. Ground shipping, First-class airmail, Pick-up ...
        required: true
      countries:
        label: Countries
        help: Apply this shipping method to certain countries
        type: multiselect
        options:
          argentina: Argentina
          belarus: Belarus
          canada: Canada
          denmark: Denmark
          ethiopia: Ethiopia
          faroeislands: Faroe Islands
      flat:
        label: Flat rate
        type: text
      item:
        label: Per item rate
        type: text
      weight:
        label: Rate by total weight
        type: textarea
      price:
        label: Rate by total price
        type: textarea
```
