### ISSUE TITLE
Field doesn't show up in `entry` parameter of structure field

### ISSUE THREAD

**Issue by samnabi** [distantnative/multiselect#7]
Nothing shows up for `{{countries[]}}` in the panel, where the content of `entry` should be.

```
  tax:
    label: Tax rates
    type: structure
    entry: {{rate}}: {{countries[]}}
    fields:
      rate:
        label: Tax rate
        type: text
      countries:
        label: Countries
        type: multiselect
        options: 
          (...)
```
